name: adityagurjar
description: My portfolio website.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+4
  intl_translation: ^0.17.9
  intl: ^0.16.1

  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  build_test: ^0.10.2

  build_web_compilers: '>=2.1.0 <3.0.0'


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/projects/
  fonts:
  - family: GoogleSansRegular
    fonts:
      - asset: assets/GoogleSansRegular.ttf

flutter_intl:
  enabled: true